### PR TITLE
it's friday

### PR DESCRIPTION
**Pull request by Yoghurt4C**
actually had to change the internals to accommodate the new pseudojson rendering system
also took the liberty to break all the indentations and compress the broken 1.72mb mod icon into 6kb

### CODE REVIEW

**Comment by Vexatos** [comment]
As usual, thank you for your work, but I'd appreciate if you didn't change the indentation of every file.

**Comment by Yoghurt4C** [comment]
it's just idea formatting, I merely wanted to quickly get rid of unused imports 😔

**Comment by Yoghurt4C** [comment]
absolutely no code changes, also tried fixing indentations; [here's a malware infested mystery build in case you're too lazy to download the jdk](https://github.com/Yoghurt4C/Flamingo/releases/download/v1.18-realb/Flamingo-1.17-1.18.jar)

**Comment by Vexatos** [comment]
I'll look at it this weekend, but thank you very much. Soon, people will be able to run Pink Flamingo version 1.18 on Minecraft version 1.17 using Java version 1.16. Truly poetic.

**Comment by Yoghurt4C** [comment]
ahead of the curve as usual

**Comment by Yoghurt4C** [comment]
thinkgen bout that weekend

**Comment by Vexatos** [comment]
'twas a long weekend, for sure.

It seems that I cannot build the gradle project. An issue with the new format. I think you forgot to include the new settings.gradle. Aside from that, this looks good to me.

**Comment by Yoghurt4C** [comment]
I don't think there's a settings file on my end. are you using the wrapper to build?

**Comment by Vexatos** [comment]
I am, adding settings.gradle from the fabric example project manually made it work, that's why I thought that'd be it.

**Comment by Yoghurt4C** [comment]
oop s!

**Comment by Vexatos** [comment]
Thank you for your work, as usual.

**Pull request merged**
