### PR TITLE
1.16 is approaching

### PR DESCRIPTION
**Pull request by Yoghurt4C**

### CODE REVIEW

**Comment by Yoghurt4C** [comment]
I was not expecting git to have this much grayon, so I can only say this
image

**Comment by Vexatos** [comment]
You should be comparing against 1.15, not master anyway

**Review by comp500 — CHANGES_REQUESTED** [review]
h

**Review by modmuss50 — APPROVED** [review]
looks fine, if these are the only changes the existing 1.15 jar might just work.

**Comment by Yoghurt4C** [comment]
should work fine on 1.16 proper

**Comment by Vexatos** [comment]
Would you mind updating the PR to build against 1.16 proper?

**Comment by Yoghurt4C** [comment]
what should the release version be? I'm not sure if I should bump it to 1.19 since 1.17 and 1.18 were bootleg

**Comment by Vexatos** [comment]
1.17 never happened. It's a myth.

**Pull request merged**
