### PR TITLE
NOISSUE prevent evil from winning

### PR DESCRIPTION
**Pull request by Yoghurt4C**
sorry I'm late
```diff
+added a crashy TESR safeguard
+moved from deprecated fapi internals
-removed the builtinitemrenderer mixin in favor of the fapi hook
```

### CODE REVIEW

**Comment by Yoghurt4C** [comment]
😭

**Comment by Vexatos** [comment]
sorry I'm late

The update does appear to work for newly placed Flamingos. However, launching a world with flamingos placed in 1.17 has all flamingos placed in the earlier version turn invisible. Breaking and replacing an invisible one works. Any idea why this might happen?

**Comment by Yoghurt4C** [comment]
that seems to be an issue only resolvable by datafixers, which require invasive injections or support for the abandoned(?) fapi pr

**Comment by Vexatos** [comment]
Sounds like pain, I guess I'll just live with it then. Code looks good otherwise, nice that mixins are no longer needed.

**Comment by Yoghurt4C** [comment]
😳

**Pull request merged**
