### PR TITLE
Wobble on right click too

### PR DESCRIPTION
**Pull request by SquidDev**
When players are in adventure mode, they can't attack blocks. As a result, they can't wobble flamingos, massively limiting the experience!

While we could mixin to allow attacking blocks in adventure mode, it's a lot more complex to do and I'm not 100% comfortable that I'd get it right. While this change isn't 100% authentic Flamingo :tm:, I think it's a suitable compromise.

### CODE REVIEW

**Comment by Vexatos** [comment]
I really don't like this change. It kind of destroys the whole purpose of the mod. I'd prefer either a patch to enable left clicking them in adventure mode, or to limit this change so right clicks are _only_ possible in adventure mode.

**Comment by SquidDev** [comment]
Fair enough! Will have a look at that tomorrow.

**Comment by SquidDev** [comment]
Done.

**Comment by Vexatos** [comment]
Code appears to work fine, thank you very much. I have no doubt that this is a great asset to future adventure maps and modding conventions alike.

**Pull request merged**
