### PR TITLE
Adapt to Forge's registry changes and extract wiggle-function.

### PR DESCRIPTION
**Pull request by iTitus**
Constants are love, constants are life :P

PS: The extraction is a prep-work for eventual OC/CC integration once those update to 1.9.

### CODE REVIEW

**Comment by Vexatos** [comment]
But there already is CC/OC integration in 1.7.10 and 1.8. Without this. Why is it needed?

**Comment by iTitus** [comment]
But not for 1.9. Does the integration (I guess it is in Computronics?) allow for a wiggle strength argument?

**Comment by Vexatos** [comment]
No? But it is not supposed to.

**Comment by asiekierka** [comment]
Keeping the code clean is a good idea anyway. Just get rid of the parameter, make it as hardcoded as possible.

**Comment by Vexatos** [comment]
...What happened there

**Comment by iTitus** [comment]
?

**Comment by iTitus** [comment]
Will fix that

**Comment by iTitus** [comment]
Fixed ;)

**Pull request merged**
