### PR TITLE
1.15

### PR DESCRIPTION
**Pull request by modmuss50**
[Flamingo-1.15-1.16.jar](https://ss.modmuss50.me/Flamingo-1.15-1.16.jar)

Might want a new branch before merging.

### CODE REVIEW

**Comment by florensie** [comment]
oman pls merge
my fabric mod depends on flamigno and is 1.15

**Comment by Ueaj-Kerman** [comment]
how to react with tiny_potato GitHub

Google

No

**Comment by hYdos** [comment]
@modmuss50 we need 1.16 snapshot updated version

**Review by hYdos — APPROVED** [review]
10/10

**Review by florensie — APPROVED** [review]

**Comment by Vexatos** [comment]
Just the right amount of wiggle.

**Pull request merged**
