### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by copygirl**
Feel free to remove the joke like, I guess.. it's not like you care about my humor anyway.. b-baka!

### CODE REVIEW

**Comment by GirafiStudios** [comment]
There is a 1.11 version of Flamingo, and the 1.9 version worked for 1.10.2, didn't it?

**Comment by copygirl** [comment]
Ahh.. whoops. This suffers from bad confusioning version syndrome!

**Comment by Vexatos** [comment]
[To newer _and_ older versions](https://github.com/asiekierka/Flamingo/releases/tag/1.0re), you mean.

**Comment by copygirl** [comment]
Mhh.. there?

**Pull request merged**
